const funFacts = [
    "The Voyager 1 spacecraft is over 15 billion miles from Earth and still sending signals.",
    "Ancient Roman concrete gets stronger over time and can harden underwater.",
    "Binary code (just 0s and 1s) powers almost everything in modern computing.",
    "A day on Venus is longer than its year.",
    "Sharks existed before trees.",
    "Bananas are naturally radioactive.",
    "Neutron stars can spin over 700 times per second.",
    "There are more possible chess games than atoms in the observable universe.",
    "The Sun loses about 4 million tons of mass every second.",

    "Bananas are technically berries, but strawberries aren't.",
    "Octopuses have three hearts and blue blood.",
    "Your stomach gets a brand-new lining every few days so it doesn't digest itself.",
    "Honey never spoils. Archaeologists have found edible honey in ancient Egyptian tombs.",
    "The Eiffel Tower grows about 15 cm taller in summer due to heat expansion.",
    "Your brain runs on roughly the same power as a 20-watt light bulb.",
    "Some turtles can breathe through their butts during hibernation.",
    "There are more possible ways to shuffle a deck of cards than there are atoms on Earth.",
    "Sloths can hold their breath longer than dolphins.",
    "The fingerprints of a koala are nearly indistinguishable from a human's.",
    "Lightning is about five times hotter than the surface of the Sun.",
    "Wombats produce cube-shaped poop.",
    "The shortest war in history lasted just 38 to 45 minutes.",
    "The smell of freshly cut grass is actually a plant distress signal.",
    "Humans share about 60% of their DNA with bananas.",
    "The Moon is slowly drifting away from Earth at about 3.8 cm per year.",
    "There are more stars in the observable universe than grains of sand on Earth's beaches.",
    "The average cloud weighs around one million pounds.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "Your bones are stronger, pound for pound, than steel.",
    "A bolt of lightning contains enough energy to toast around 100,000 slices of bread.",
    "The first alarm clock could only ring at 4:00 a.m.",
    "Scotland's national animal is the unicorn.",
    "Some frogs can survive being frozen solid and thaw back to life.",
    "The human nose can detect over one trillion different scents.",
    "An astronaut can grow up to 2 inches taller in space.",
    "The world's oldest known recipe is for beer.",
    "Crows can recognize individual human faces and remember them for years.",
    "Polar bears have black skin beneath their white fur.",
    "The first oranges weren't orange-they were green.",
    "A blue whale's heart is about the size of a small car.",
    "Hot water can freeze faster than cold water under certain conditions.",
    "Butterflies taste with their feet.",
    "Every human spent about nine months as a single cell.",
    "The inventor of the Pringles can is buried in one.",
    "Jellyfish have existed longer than dinosaurs.",
    "Your left lung is smaller than your right to make room for your heart.",
    "The dot over the letters 'i' and 'j' is called a tittle.",
    "Some bamboo species can grow over 3 feet in a single day.",
    "The shortest commercial flight in the world lasts under two minutes.",
    "Cats can't taste sweetness.",
    "The world's largest desert is Antarctica.",
    "The first computer bug was an actual moth found inside a computer.",
    "Glass isn't a liquid-it's an amorphous solid.",
    "An apple, potato, and onion all taste nearly identical if you eat them with your nose plugged.",
    "Humans glow in the dark, but the light is too faint for our eyes to detect.",
    "The longest hiccuping spree lasted 68 years.",
    "Rats laugh when they're tickled.",
    "The hashtag symbol is officially called an octothorpe.",
    "A teaspoon of neutron star material would weigh billions of tons on Earth.",
    "The average person walks enough in a lifetime to circle Earth several times.",
    "There are trees alive today that were already ancient when the pyramids were built.",
    "A single sneeze can travel over 100 miles per hour.",
    "Space is completely silent because sound needs matter to travel.",
    "Pineapples take about two years to grow.",
    "Some metals explode when they touch water.",
    "The world's largest snowflake reportedly measured 15 inches across.",
    "Elephants can recognize themselves in mirrors.",
    "You can't hum while holding your nose closed.",
    "The world's oceans contain enough gold to give every person billions of dollars' worth-it's just too diluted to extract economically.",
    "The first camera required people to sit still for several minutes.",
    "Flamingos are naturally gray and turn pink from their diet.",
    "The average person produces enough saliva in a lifetime to fill two swimming pools.",
    "The largest volcano in the Solar System is on Mars.",
    "Koalas sleep up to 22 hours a day.",
    "A cloud can float because the tiny water droplets are spread over an enormous volume of air.",
    "The world's oldest known living tree is over 4,800 years old.",
    "A group of flamingos is called a flamboyance.",
    "The inventor of the microwave oven discovered it after a chocolate bar melted in his pocket.",
    "Some spiders can fly by riding electric fields in the atmosphere.",
    "The human eye can distinguish around 10 million different colors.",
    "There are more possible Rubik's Cube combinations than 43 quintillion.",
    "Ancient Romans used crushed mouse brains as toothpaste.",
    "The average person spends about six months of their life waiting for traffic lights.",
    "Goats have rectangular pupils.",
    "The first email was sent before the first mobile phone call.",
    "A bolt of lightning is only about an inch wide, despite looking much larger.",
    "There are lakes beneath Antarctica's ice that have been sealed off for millions of years.",
    "The word 'robot' comes from a Czech word meaning 'forced labor.'",
    "Penguins propose to their mates by offering a smooth pebble.",
    "Your heart creates enough pressure to squirt blood over 30 feet.",
    "The smell after rain has its own name: petrichor.",
    "A group of owls is called a parliament.",
    "The first recorded Olympic champion was a cook.",
    "The human body contains enough carbon to make about 900 pencils.",
    "Coconuts kill more people each year than sharks.",
    "Some fish can climb trees.",
    "Your body replaces most of its atoms over time, meaning you're literally made of mostly different matter than you were years ago.",
    "Saturn would float in a bathtub large enough to hold it because it's less dense than water.",
    "The largest living organism on Earth is a single fungus covering several square miles.",
    "There are more fake flamingos in the world than real ones.",
    "A shrimp's heart is located in its head.",
    "The universe is expanding faster today than it was billions of years ago.",
    "The first person to reach the speed of sound didn't hear the sonic boom—they were ahead of it.",
    "Every atom in your body was forged inside an ancient star.",
    "The shortest complete sentence in English is 'I am.'",
    "A single teaspoon of healthy soil contains more living organisms than there are people on Earth.",
    "The human body contains enough iron to make a small nail.",
    "There are waterfalls beneath the ocean, caused by differences in water density.",
    "The first video uploaded to YouTube was only 19 seconds long.",
    "A cockroach can survive for weeks without its head.",
    "The largest living structure on Earth is the Great Barrier Reef, visible from space under the right conditions.",
    "Some volcanoes erupt blue lava, caused by burning sulfur.",
    "The average person blinks around 20,000 times a day.",
    "There is enough DNA in one human body to stretch from the Earth to the Sun and back hundreds of times.",
    "Owls cannot move their eyes-they rotate their heads instead.",
    "The world's deepest fish has been found over 8,000 meters below sea level.",
    "A teaspoon of a neutron star would outweigh Mount Everest.",
    "The coldest naturally recorded temperature on Earth was below -128°F (-89°C).",
    "Some mushrooms create zombies by controlling insects.",
    "Every minute, around 300 hours of video are uploaded to YouTube.",
    "The average human heart beats over 2.5 billion times in a lifetime.",
    "The Sun contains over 99.8% of the Solar System's mass.",
    "A single bolt of lightning can contain up to one billion volts.",
    "The world's tallest tree is taller than the Statue of Liberty.",
    "Octopus arms can continue reacting to stimuli even after being separated from the body.",
    "A giraffe only needs about 30 minutes to 2 hours of sleep each day.",
    "Some birds intentionally decorate their homes to attract mates.",
    "The world's oldest known message in a bottle spent over 130 years at sea.",
    "A person's sense of smell is stronger while they are asleep than when awake.",
    "The average smartphone has millions of times more computing power than the computers used for the Apollo Moon missions.",
    "Some deep-sea creatures create their own light through bioluminescence.",
    "An adult human has fewer bones than a baby because many fuse together over time.",
    "The fastest-growing plant on Earth is bamboo.",
    "Venus is the hottest planet in the Solar System despite not being closest to the Sun.",
    "Some whales have songs that evolve over time like popular music.",
    "There are caves containing crystals as large as telephone poles.",
    "The average raindrop falls at about 14 to 20 mph.",
    "Some deserts get colder than Antarctica during certain nights.",
    "There are sharks that glow in the dark.",
    "The first website ever created is still online.",
    "The tallest mountain measured from base to summit is Mauna Kea, not Mount Everest.",
    "An iceberg can hide over 90% of its mass below the water's surface.",
    "Some ants can carry more than 50 times their own body weight.",
    "The human brain contains roughly 86 billion neurons.",
    "Earth is struck by about 100 lightning bolts every second.",
    "There are lakes that can suddenly explode due to trapped gases.",
    "Some parrots can solve logic puzzles designed for young children.",
    "The smell of vanilla can reduce feelings of stress for some people.",
    "The first known vending machine dispensed holy water.",
    "A snowstorm can produce thunder, a phenomenon called thundersnow.",
    "The oldest living sharks are older than the United States.",
    "Some insects can survive being frozen for months.",
    "Earth's core is nearly as hot as the surface of the Sun.",
    "The first barcode scanned at a grocery store was on a pack of chewing gum.",
    "Sea cucumbers can eject parts of their organs to escape predators.",
    "Some birds can sleep while flying.",
    "The average cumulus cloud moves at around 25 to 35 mph.",
    "There are fish that can survive out of water for days.",
    "The Pacific Ocean is wider than the Moon.",
    "A single redwood tree can live for over 2,000 years.",
    "The world's largest cave has its own jungle and weather system inside.",
    "Some turtles glow under ultraviolet light.",
    "The smell of cinnamon has been shown to improve alertness in some studies.",
    "A camel's hump stores fat, not water.",
    "Earth is the only known planet not named after a god.",
    "Some butterflies migrate thousands of miles across continents.",
    "The longest mountain range on Earth is underwater.",
    "There are more molecules in one glass of water than glasses of water in Earth's oceans.",
    "The first emoji was created in Japan in 1999.",
    "Some crabs decorate themselves with living sea creatures as camouflage.",
    "The average person dreams for about six years of their life.",
    "There are bacteria that can survive inside nuclear reactors.",
    "The human eye can detect a candle flame from over a mile away on a dark night.",
    "Some frogs carry their babies inside their mouths.",
    "The hottest pepper in the world is so spicy it requires protective gear to process.",
    "A single teaspoon of honey represents the lifetime work of about 12 bees.",
    "Some planets rain liquid diamonds deep in their atmospheres.",
    "The average person spends about one-third of their life sleeping.",
    "There are jellyfish that can revert back to an earlier stage of life.",
    "The world's largest flower can grow over three feet across.",
    "A day on Pluto lasts over six Earth days.",
    "Some species of bamboo flower only once every 100 years.",
    "Your body creates about 25 million new cells every second.",
    "There are caves with underground rivers longer than 100 miles.",
    "Some lizards can squirt blood from their eyes as a defense mechanism.",
    "The average tornado travels at about 30 mph across the ground.",
    "A hummingbird's wings can beat more than 50 times per second.",
    "There are stars so large that, if placed where our Sun is, they would extend past Jupiter.",
    "The Earth's magnetic field flips polarity every few hundred thousand years on average.",
    "Some snails can sleep for up to three years.",
    "The world's largest living bird is the ostrich.",
    "A full-grown giant squid's eyes can be larger than a basketball.",
    "Some coral reefs can be thousands of years old.",
    "The first webcam was created to monitor a coffee pot.",
    "The average person speaks around 7,000 words per day.",
    "Some spiders keep tiny frogs as roommates because they eat pests.",
    "The deepest point in the ocean has pressure over 1,000 times greater than at sea level.",
    "The first mechanical clocks had no minute hands.",
    "Some plants can recognize when neighboring plants are their relatives.",
    "Earth receives enough sunlight in one hour to power humanity for about a year.",
    "The largest hailstone ever recorded was about the size of a volleyball.",
    "Every breath you take likely contains at least a few atoms once breathed by dinosaurs.",
];



function displayRandomFacts() {
    const list = document.getElementById("fun-facts-list");

    if (!list) return;

    list.innerHTML = "";

    // Copy the array so the original isn't modified
    const shuffled = [...funFacts];

    // Fisher-Yates shuffle
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }

    // Show the first four
    shuffled.slice(0, 4).forEach(fact => {
        const li = document.createElement("li");
        li.textContent = fact;
        list.appendChild(li);
    });
}

displayRandomFacts();

setInterval(displayRandomFacts, 30000);
